services:
  ubuntu-ssh:
    build: .
    container_name: neonx_ai_agent
    ports:
      - "2222:22"
      - "18789:18789"
    restart: unless-stopped
    volumes:
      - agent-data:/root
    networks:
      - neonx-network

networks:
  neonx-network:
    external: true

volumes:
  agent-data: