services:
  ubuntu-ssh:
    build: .
    container_name: neonx_ai_agent
    ports:
      - "2222:22"
    restart: unless-stopped
    volumes:
      - agent-data:/root/.openclaw
    networks:
      - neonx-network

networks:
  neonx-network:
    external: true

volumes:
  agent-data: