services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    container_name: neonx-ai-agent

    restart: unless-stopped

    stdin_open: true
    tty: true

    # command: openclaw gateway

    volumes:
      - openclaw-data:/home/node

    networks:
      - neonx-network

networks:
  neonx-network:
    external: true

volumes:
  openclaw-data: