#!/bin/sh
# Module: Codex CLI custom provider setup
# Points the Codex CLI at the same AI gateway + model that OpenClaw uses,
# so the openclaw-codex-app-server plugin runs Codex on the configured model
# instead of requiring an OpenAI account.
#
# Codex reads $CODEX_HOME/config.toml. We (re)generate one config.toml for
# the user-scoped home ($HOME/.codex) and every agent-scoped codex-home,
# using the same values config/models.sh writes into openclaw.json:
#   BASE_URL  -> model_providers.<id>.base_url
#   API_KEY   -> env var referenced via env_key (already set in the container)
#   MODEL     -> model name (provider prefix stripped)
#
# Current Codex CLI releases only support the Responses wire protocol for
# custom providers. OpenClaw may still use Chat Completions independently.

CONFIG_PATH="/home/node/.openclaw"
CONFIG="$CONFIG_PATH/openclaw.json"
AGENTS_DIR="$CONFIG_PATH/agents"

BASE_URL="${BASE_URL:-http://ai_gateway:20128/v1}"
WIRE_API="responses"

# Resolve primary model from openclaw.json (written by config/models.sh),
# e.g. "neonx/neonx-3.0-plus" -> provider "neonx", model "neonx-3.0-plus".
PRIMARY_MODEL=""
if command -v jq >/dev/null 2>&1 && [ -f "$CONFIG" ]; then
    PRIMARY_MODEL=$(jq -r '.agents.defaults.model.primary // empty' "$CONFIG" 2>/dev/null)
fi
[ -n "$PRIMARY_MODEL" ] || PRIMARY_MODEL="${MODEL:-}"
if [ -z "$PRIMARY_MODEL" ]; then
    echo "Codex provider: no model configured, skipping"
    return 0 2>/dev/null || exit 0
fi

case "$PRIMARY_MODEL" in
    */*)
        PROVIDER_ID="${PRIMARY_MODEL%%/*}"
        MODEL_NAME="${PRIMARY_MODEL#*/}"
        ;;
    *)
        PROVIDER_ID="${MODEL_PROVIDER:-neonx}"
        MODEL_NAME="$PRIMARY_MODEL"
        ;;
esac

# write_config <codex_home>
# Regenerates <codex_home>/config.toml with the custom provider.
write_config() {
    codex_home="$1"
    [ -n "$codex_home" ] || return 0
    mkdir -p "$codex_home" || return 0

    cat > "$codex_home/config.toml" <<EOF
# Generated by bootstrap/modules/plugins/codex-provider.sh - do not edit.
model_provider = "$PROVIDER_ID"
model = "$MODEL_NAME"
# Docker commonly blocks the user namespaces required by bubblewrap.
sandbox_mode = "danger-full-access"
approval_policy = "never"

[model_providers.$PROVIDER_ID]
name = "$PROVIDER_ID"
base_url = "$BASE_URL"
env_key = "API_KEY"
wire_api = "$WIRE_API"
EOF
    echo "Codex provider: wrote $codex_home/config.toml (model=$MODEL_NAME, wire_api=$WIRE_API)"
}

configured_any=0

# 1) Agent-scoped Codex homes: <agents>/<id>/agent/codex-home
if [ -d "$AGENTS_DIR" ]; then
    for agent_dir in "$AGENTS_DIR"/*/agent; do
        [ -d "$agent_dir" ] || continue
        write_config "$agent_dir/codex-home"
        configured_any=1
    done
fi

# On a fresh client the gateway has never started, so no agent dir exists yet.
# Pre-create the Codex home for the default agent ids (same logic as codex-skills.sh).
if [ "$configured_any" -eq 0 ]; then
    agent_ids=""
    if command -v jq >/dev/null 2>&1 && [ -f "$CONFIG" ]; then
        agent_ids="$(jq -r '.agents.list[]?.id // empty' "$CONFIG" 2>/dev/null | tr '\n' ' ')"
    fi
    [ -n "$agent_ids" ] || agent_ids="main"
    for id in $agent_ids; do
        write_config "$AGENTS_DIR/$id/agent/codex-home"
        configured_any=1
    done
fi

# 2) User-scoped Codex home: $HOME/.codex (covers homeScope "user")
if [ -n "${HOME:-}" ]; then
    write_config "$HOME/.codex"
    configured_any=1
fi

if [ "$configured_any" -eq 0 ]; then
    echo "Codex provider: no Codex home found, nothing configured"
fi

return 0 2>/dev/null || exit 0
