name: ${STACK_NAME:-neonx-ai-agent}

services:
  ai_agent:
    image: ghcr.io/openclaw/openclaw:2026.7.1
    # container_name: ${CONTAINER_NAME:-neonx_ai_agent}

    restart: unless-stopped

    stdin_open: true
    tty: true

    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    user: "0:0"

    volumes:
      - ./agent_data:/home/node/.openclaw
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./openclaw-message-listener/dist:/app/dist/extensions/openclaw-message-listener:ro
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
      OPENCLAW_GATEWAY_PASSWORD: "changeme"
      OPENCLAW_HOME: /home/node
      BASE_URL: ${BASE_URL:-http://ai_gateway:20128/v1}
      API_KEY: ${API_KEY:-sk-aea5c2d612c2e3dd-sd6l75-8a587593}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      FACEBOOK_PAGE_ID: ${FACEBOOK_PAGE_ID:-}
      FACEBOOK_PAGE_ACCESS_TOKEN: ${FACEBOOK_PAGE_ACCESS_TOKEN:-}
      STACK_NAME: ${STACK_NAME:-neonx-ai-agent}

    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.0"
    #       memory: 512M
    #     reservations:
    #       cpus: "0.25"
    #       memory: 128M

    expose:
      - "18789"
      - "8001" # For download files from the agent
      
    # ports:
    #   - "18789:18789"
    #   - "8001:8001" # For download files from the agent
    networks:
      neonx-network:
        aliases:
          - ${STACK_NAME:-neonx-ai-agent}

networks:
  neonx-network:
    external: true